In [1]:
pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\diksh\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: psycopg2-binary in c:\users\diksh\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in c:\users\diksh\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\diksh\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
df = pd.read_csv("../Data/cleaned/DataCoSupplyChainDataset_cleaned.csv", encoding = 'latin1')
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Region,Order State,Order Status,Product Card Id,Product Category Id,Product Image,Product Name,Product Price,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,Southeast Asia,Java Occidental,COMPLETE,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,South Asia,RajastÃ¡n,PENDING,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,South Asia,RajastÃ¡n,CLOSED,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,Oceania,Queensland,COMPLETE,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,Oceania,Queensland,PENDING_PAYMENT,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,1/15/2018 11:24,Standard Class

In [3]:
engine = create_engine(
    "postgresql+psycopg2://postgres:SQL1924@localhost:5432/supply_chain_analysis"
)

In [4]:
with engine.connect() as conn:
    print("Connected successfully!")

Connected successfully!

In [5]:
df.to_sql(
    "supply_chain",
    engine,
    if_exists="replace",
    index=False
)

54

In [6]:
query = """
SELECT
  COUNT(*) as total_deliveries,

  COUNT(*) FILTER ( WHERE "Delivery Status" = 'Shipping on time') AS on_time_deliveries,

  ROUND(
  100.0 * COUNT(*) FILTER(
  WHERE "Delivery Status" = 'Shipping on time'
  )/COUNT(*),2) AS overall_ontime_rate

FROM supply_chain;  
"""

overall_ontime = pd.read_sql(query, engine)

overall_ontime

   total_deliveries  on_time_deliveries  overall_ontime_rate
0            180519               32196                17.84

In [19]:
query = """
SELECT
  COUNT(*) as total_deliveries,

  COUNT(*) FILTER ( WHERE "Delivery Status" = 'Late delivery') AS Late_deliveries,

  ROUND(
  100.0 * COUNT(*) FILTER(
  WHERE "Delivery Status" = 'Late delivery'
  )/COUNT(*),2) AS Late_Delivery_rate

FROM supply_chain;  
"""

Late_Delivery = pd.read_sql(query, engine)

Late_Delivery

   total_deliveries  late_deliveries  late_delivery_rate
0            180519            98977               54.83

In [12]:
query = """
SELECT 
 AVG("Days for shipping (real)") AS Avg_real_shipping, 
 AVG("Days for shipment (scheduled)") AS Avg_schedule_shipping ,
 (AVG("Days for shipping (real)") - AVG("Days for shipment (scheduled)")) AS Avg_shipping_difference
FROM supply_chain;
"""

avg_delivery_time = pd.read_sql(query, engine)
avg_delivery_time

   avg_real_shipping  avg_schedule_shipping  avg_shipping_difference
0           3.497654               2.931847                 0.565807

In [25]:
query="""
SELECT
  "Order Region",
  COUNT(*) as total_deliveries,
  COUNT(*) FILTER(WHERE "Delivery Status" = 'Shipping on time') AS On_time_delivery,
  ROUND(
  100.0 * COUNT(*) FILTER(
  WHERE "Delivery Status" = 'Shipping on time')
  / NULLIF(COUNT(*), 0), 2) AS regional_ontime_rate

FROM supply_chain
GROUP BY "Order Region"
ORDER BY regional_ontime_rate DESC
LIMIT 5;
"""

best_regional_delivery = pd.read_sql(query,engine)
best_regional_delivery

   Order Region  total_deliveries  on_time_delivery  regional_ontime_rate
0  Central Asia               553               124                 22.42
1   West Africa              3696               769                 20.81
2    US Center               5887              1174                 19.94
3       Oceania             10148              1927                 18.99
4   East Africa              1852               346                 18.68

In [24]:
query="""
SELECT
  "Order Region",
  COUNT(*) as total_deliveries,
  COUNT(*) FILTER(WHERE "Delivery Status" = 'Shipping on time') AS On_time_delivery,
  ROUND(
  100.0 * COUNT(*) FILTER(
  WHERE "Delivery Status" = 'Shipping on time')
  / NULLIF(COUNT(*), 0), 2) AS regional_ontime_rate

FROM supply_chain
GROUP BY "Order Region"
ORDER BY regional_ontime_rate ASC
LIMIT 5;
"""

worst_regional_delivery = pd.read_sql(query,engine)
worst_regional_delivery

     Order Region  total_deliveries  on_time_delivery  regional_ontime_rate
0          Canada               959               157                 16.37
1  South of  USA               4045               672                 16.61
2  Western Europe             27109              4589                 16.93
3  Southeast Asia              9539              1631                 17.10
4  Central Africa              1677               290                 17.29

In [11]:
query="""
SELECT
   "Shipping Mode",
   COUNT(*) as total_delivery,
   COUNT(*) FILTER(WHERE "Delivery Status" = 'Shipping on time') AS on_time_delivery,
   ROUND(
   100.0 * COUNT(*) FILTER(WHERE "Delivery Status" = 'Shipping on time') / 
   NULLIF(COUNT(*), 0),2) AS ontime_rate,
   ROUND(
   100.0 * COUNT(*) FILTER(
   WHERE "Delivery Status" = 'Late delivery'
   )/COUNT(*),2) AS Late_Delivery_rate
FROM supply_chain
GROUP BY "Shipping Mode"
ORDER BY ontime_rate DESC
"""

shipping_mode = pd.read_sql(query, engine)
shipping_mode

,Shipping Mode,total_delivery,on_time_delivery,ontime_rate,late_delivery_rate
0,Same Day,9737,4839,49.70,45.74
1,Second Class,35216,6819,19.36,76.63
2,Standard Class,107752,20538,19.06,38.07
3,First Class,27814,0,0.00,95.32

In [5]:
query= """
SELECT 
   "Category Name",
   ROUND(
   100.0 * COUNT(*) FILTER(WHERE "Delivery Status" = 'Late delivery') 
   / NULLIF(COUNT(*), 0),2) AS "Late Delivery Rate"
FROM supply_chain
GROUP BY "Category Name"
ORDER BY "Late Delivery Rate" DESC
"""

product_category= pd.read_sql(query,engine)
product_category

           Category Name  Late Delivery Rate
0      Golf Bags & Carts               68.85
1               Lacrosse               60.06
2           Pet Supplies               58.94
3               Cameras                58.11
4      Strength Training               57.66
5        As Seen on  TV!               57.35
6                  Music               57.14
7            Accessories               56.97
8    Fitness Accessories               56.96
9                 Books                56.54
10      Women's Clothing               56.46
11          Boxing & MMA               56.26
12           Golf Gloves               56.26
13    Hunting & Shooting               56.14
14           Electronics               56.08
15                Crafts               55.99
16     Health and Beauty               55.80
17                Garden               55.79
18      Tennis & Racquet               55.79
19              Trade-In               55.65
20            Golf Shoes               55.53
21        Sporting Goods               55.46
22        Girls' Apparel               55.29
23            Basketball               55.22
24  Consumer Electronics               55.22
25   Baseball & Softball               55.22
26         Shop By Sport               55.15
27                  Toys               55.01
28                Cleats               54.97
29               Fishing               54.93
30          Water Sports               54.81
31  Indoor/Outdoor Games               54.75
32            Golf Balls               54.58
33       Women's Apparel               54.56
34      Camping & Hiking               54.53
35      Cardio Equipment               54.50
36        Men's Footwear               54.49
37                Soccer               54.35
38        Men's Clothing               54.33
39           Video Games               54.30
40                  DVDs               53.62
41    Women's Golf Clubs               53.59
42                Hockey               53.58
43      Kids' Golf Clubs               53.39
44   Children's Clothing               53.37
45                 Baby                52.66
46                  CDs                52.03
47          Golf Apparel               51.93
48             Computers               50.68
49      Men's Golf Clubs               47.70

In [12]:
query = """ 
SELECT
    "Customer Segment",
    COUNT(*) AS total_orders,
    COUNT(*) FILTER (
        WHERE "Delivery Status" = 'Late delivery'
    ) AS late_orders,
    ROUND(
        100.0 * COUNT(*) FILTER (
            WHERE "Delivery Status" = 'Late delivery'
        ) / NULLIF(COUNT(*), 0),
        2
    ) AS late_delivery_rate
FROM supply_chain
GROUP BY "Customer Segment"
ORDER BY late_delivery_rate DESC;
"""
Customer_segment= pd.read_sql(query,engine)
Customer_segment

  Customer Segment  total_orders  late_orders  late_delivery_rate
0      Home Office         32226        17747               55.07
1         Consumer         93504        51248               54.81
2        Corporate         54789        29982               54.72